
[functions.paddle-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/paddle-webhook/deno.json"
entrypoint = "./functions/paddle-webhook/index.ts"

[functions.signup]
verify_jwt = false

[functions.signin]
verify_jwt = false

[functions.set-org-claims]
verify_jwt = false

[functions.create-custom-price]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.cleanup-orphaned-orgs]
verify_jwt = false

[functions.license-expiration-checker]
verify_jwt = false

[functions.reset-password-request]
verify_jwt = false

[functions.confirm-password-reset]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-invitation-token]
verify_jwt = false

[functions.add-subscription-items]
verify_jwt = false

[functions.schedule-license-change]
verify_jwt = false

[functions.apply-scheduled-license-changes]
verify_jwt = false

[functions.send-quote-request]
verify_jwt = false

[functions.assign-trial-user]
verify_jwt = false

[functions.send-verification-reminders]
verify_jwt = false
